sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
addons:
  postgresql: "9.6"
before_install:
  - sudo service postgresql stop
  - echo "max_prepared_transactions = 10" | sudo tee -a /etc/postgresql/9.6/main/postgresql.conf
  - sudo service postgresql start 9.6
install:
  - pip install tox-travis
  - pip install asyncpg || true
before_script:
  - createuser -U postgres -s scott
  - psql -c "create database test with owner=scott encoding='utf8' template=template0;" -U postgres
  - psql -c 'CREATE SCHEMA test_schema' -U scott test
  - psql -c 'CREATE SCHEMA test_schema_2' -U scott test
  - psql -c 'create extension hstore' -U postgres test
script: tox
